# Generated by Django 5.2.3 on 2025-06-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_cover_image_alter_album_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover_image',
            new_name='album_cover',
        ),
    ]
